### ISSUE TITLE
Review FR localizations

### ISSUE THREAD

**Issue by birdsarah** [mozilla-l10n/mozilla-vpn-website-l10n#1]
Unfortunately, we don't yet have a good way for localizers to view all the translations (we're working on it).

3 out of 4 urls can be viewed easily, one can't. Posting screenshots for all here:

## Login Success

https://guardian-dev.herokuapp.com/vpn/client/login/success

![Screenshot from 2021-03-29 12-22-53](https://user-images.githubusercontent.com/1796208/112875246-90408980-9089-11eb-834e-b93062657182.png)

## Login Fail

https://guardian-dev.herokuapp.com/vpn/client/login/error

![Screenshot from 2021-03-29 12-23-53](https://user-images.githubusercontent.com/1796208/112875310-a4848680-9089-11eb-9e36-be71c3e9fad0.png)

## 404

https://guardian-dev.herokuapp.com/vpn/notapage

![Screenshot from 2021-03-29 12-24-17](https://user-images.githubusercontent.com/1796208/112875372-b6662980-9089-11eb-9c1a-4408e0b9ae61.png)

## Download page and menu

https://guardian-dev.herokuapp.com/vpn/download (requires login with mozilla account)

![Screenshot from 2021-03-29 12-25-29](https://user-images.githubusercontent.com/1796208/112875601-0218d300-908a-11eb-9651-808fa7dc760f.png)
![Screenshot from 2021-03-29 12-26-27](https://user-images.githubusercontent.com/1796208/112875609-0644f080-908a-11eb-84dd-fc7df0f1e228.png)

**Comment by birdsarah** [comment]
For the last link (download page) where the english version cannot be accessed publicly, here is the en-US screen grab

![Screenshot from 2021-03-29 12-34-14](https://user-images.githubusercontent.com/1796208/112876520-3b057780-908b-11eb-9e83-2094d427ea83.png)
![Screenshot from 2021-03-29 12-34-27](https://user-images.githubusercontent.com/1796208/112876536-422c8580-908b-11eb-80dd-4182e5a17c56.png)

**Comment by flodolo** [comment]
@TheoChevalier 
FYI, if you want to review the current French translation.

**Comment by TheoChevalier** [comment]
> @TheoChevalier
> FYI, if you want to review the current French translation.

Thanks, I’ve slightly tweaked the app store buttons

**Comment by flodolo** [comment]
@birdsarah 
Any chance you could add an updated screenshot of the Download page, once the [changes](https://github.com/mozilla-l10n/mozilla-vpn-website-l10n/commit/7eb9b51a01b465743e5c0a39ef97a10e9f893fea) are imported in the main repo?

**Comment by birdsarah** [comment]
Absolutely!

**Comment by birdsarah** [comment]
Here's the latest.

![Screenshot from 2021-03-30 14-53-38](https://user-images.githubusercontent.com/1796208/113048147-d0763980-9167-11eb-9ad0-5458e401ec4e.png)
![Screenshot from 2021-03-30 14-53-49](https://user-images.githubusercontent.com/1796208/113048157-d3712a00-9167-11eb-81cd-be91c1bc0450.png)

**Comment by birdsarah** [comment]
@TheoChevalier @flodolo - does this look good for sign-off?

**Comment by flodolo** [comment]
It looks good to me, based on the changes I see in Pontoon.

**Comment by birdsarah** [comment]
I'm going to close this issue based on @flodolo's comment. If additional changes need to be made, don't hesitate to re-open. I think we've got a great first pass though. Thanks!
