### ISSUE TITLE
Review DE localizations

### ISSUE THREAD

**Issue by birdsarah** [mozilla-l10n/mozilla-vpn-website-l10n#2]
Unfortunately, we don't yet have a good way for localizers to view all the translations (we're working on it).

3 out of 4 urls can be viewed easily, one can't. Posting screenshots for all here:

## Login Success

https://guardian-dev.herokuapp.com/vpn/client/login/success

![Screenshot from 2021-03-29 12-30-04](https://user-images.githubusercontent.com/1796208/112876020-97b46280-908a-11eb-83c7-1d23fa7a383f.png)

## Login Fail

https://guardian-dev.herokuapp.com/vpn/client/login/error

![Screenshot from 2021-03-29 12-30-11](https://user-images.githubusercontent.com/1796208/112876032-9be08000-908a-11eb-9728-295b0cc29076.png)

## 404

https://guardian-dev.herokuapp.com/vpn/notapage

![Screenshot from 2021-03-29 12-30-21](https://user-images.githubusercontent.com/1796208/112876051-a0a53400-908a-11eb-9899-6e0144772e29.png)

## Download page and menu

https://guardian-dev.herokuapp.com/vpn/download (requires login with mozilla account)

![Screenshot from 2021-03-29 12-29-09](https://user-images.githubusercontent.com/1796208/112876077-a8fd6f00-908a-11eb-855d-cf345229703b.png)
![Screenshot from 2021-03-29 12-32-58](https://user-images.githubusercontent.com/1796208/112876264-ea8e1a00-908a-11eb-9f2a-f558a0f9d415.png)

**Comment by birdsarah** [comment]
For the last link (download page) where the english version cannot be accessed publicly, here is the en-US screen grab

![Screenshot from 2021-03-29 12-34-14](https://user-images.githubusercontent.com/1796208/112876520-3b057780-908b-11eb-9e83-2094d427ea83.png)
![Screenshot from 2021-03-29 12-34-27](https://user-images.githubusercontent.com/1796208/112876536-422c8580-908b-11eb-80dd-4182e5a17c56.png)

**Comment by flodolo** [comment]
@koehlermichael
In case you want to double check your localization for German, since we don't have a test site yet.

**Comment by koehlermichael** [comment]
Thank you. Just to be sure, there is no known issue with these pages, the screenshots are just a way to review the localization without a test site, correct?

If so, all is well, as far as I can see.

**Comment by flodolo** [comment]
Correct, no known issues. This is currently the only way to review translations in place, since setting up the test pages is taking longer than expected.

I'll close the issue then, thanks for checking.
